"""
Legal Chunk Augmentor (Summary-Augmented Chunking)
====================================================

Spec 04 — Summary-Augmented Chunking (SAC)

Attaches a short factual summary to each static-law chunk before embedding.
The summary captures:
  - what issue the clause regulates
  - who the regulated subject is
  - the main condition / exception
  - what legal area the source belongs to

Summaries are generated by LLM and cached by clause-text hash to avoid
re-generating on incremental refreshes.

Usage:
    augmentor = LegalChunkAugmentor()
    summary = await augmentor.summarize_clause(clause)
    augmented_text = await augmentor.augment_clause_text(clause)
"""
from __future__ import annotations

import hashlib
import logging
from typing import Optional

from app.services.models.legal_document import LegalClause

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# In-memory summary cache — keyed by SHA-256 hash of clause text.
# On a production system this should be a Redis or DB-backed cache.
# ---------------------------------------------------------------------------
_summary_cache: dict[str, str] = {}


def _text_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


class LegalChunkAugmentor:
    """
    Generates and caches short legal summaries for clause chunks.

    Strategy:
      1. Check in-memory cache first (hash of clause text).
      2. If no LLM provider is given, fall back to a rule-based summary.
      3. If LLM is given, ask the LLM for a 1-3 sentence factual summary.
    """

    _SYSTEM_PROMPT = (
        "Bạn là chuyên gia pháp lý. "
        "Tóm tắt đoạn điều khoản pháp luật sau trong 1-3 câu ngắn gọn, súc tích. "
        "Nêu rõ: (1) điều khoản quy định về vấn đề gì, (2) đối tượng điều chỉnh là ai hoặc là gì, "
        "(3) điều kiện hoặc ngoại lệ chính (nếu có). "
        "Không thêm nhận định pháp lý chủ quan. Trả lời bằng tiếng Việt."
    )

    def __init__(self, llm_provider=None):
        """
        Args:
            llm_provider: Optional LLM provider from app.services.llm.get_llm_provider().
                          If None, falls back to rule-based heuristic summaries.
        """
        self._llm = llm_provider

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def summarize_clause(self, clause: LegalClause) -> str:
        """
        Generate a 1-3 sentence factual summary for a LegalClause.

        Returns an empty string if the clause is too short to summarize.
        Caches the result by text hash to avoid duplicate LLM calls.
        """
        if len(clause.text.strip()) < 80:
            return ""

        cache_key = _text_hash(clause.text)
        if cache_key in _summary_cache:
            return _summary_cache[cache_key]

        summary = await self._generate_summary(clause)
        _summary_cache[cache_key] = summary
        return summary

    async def augment_clause_text(self, clause: LegalClause) -> str:
        """
        Return the full augmented embedding text for a clause.

        If the clause already has a summary_text, use it directly.
        Otherwise generate one via LLM / rule-based heuristic.
        """
        if not clause.summary_text:
            clause.summary_text = await self.summarize_clause(clause)
        return clause.to_chunk_text()

    # ------------------------------------------------------------------
    # Internal generation
    # ------------------------------------------------------------------

    async def _generate_summary(self, clause: LegalClause) -> str:
        """Try LLM first, fall back to heuristic."""
        if self._llm is not None:
            try:
                return await self._llm_summarize(clause)
            except Exception as e:
                logger.warning(f"LLM summary failed for clause {clause.clause_id}: {e}")

        return self._heuristic_summary(clause)

    async def _llm_summarize(self, clause: LegalClause) -> str:
        """Call LLM provider to generate a factual summary."""
        context_parts = []
        if clause.title:
            context_parts.append(f"Văn bản: {clause.title}")
        if clause.document_type:
            context_parts.append(f"Loại: {clause.document_type}")
        if clause.article:
            context_parts.append(f"Điều: {clause.article}")
        if clause.clause:
            context_parts.append(f"Khoản: {clause.clause}")

        context_line = " | ".join(context_parts)
        user_prompt = f"{context_line}\n\nNội dung điều khoản:\n{clause.text[:2000]}"

        # Use the provider's generate or chat method
        if hasattr(self._llm, "generate"):
            raw = await self._llm.generate(
                system=self._SYSTEM_PROMPT,
                user=user_prompt,
                max_tokens=200,
            )
        elif hasattr(self._llm, "chat"):
            from app.services.llm.types import Message
            messages = [
                Message(role="system", content=self._SYSTEM_PROMPT),
                Message(role="user", content=user_prompt),
            ]
            raw = await self._llm.chat(messages=messages, max_tokens=200)
        else:
            return ""

        # Strip markdown fences if model returns them
        summary = raw.strip().strip("`").strip()
        return summary[:500]

    @staticmethod
    def _heuristic_summary(clause: LegalClause) -> str:
        """
        Rule-based heuristic summary when no LLM is available.

        Extracts the first meaningful sentence(s) and annotates
        with the document context so the chunk is still more
        descriptive than raw text alone.
        """
        parts: list[str] = []
        if clause.document_type:
            parts.append(f"({clause.document_type})")
        if clause.issuing_authority:
            parts.append(f"ban hành bởi {clause.issuing_authority}")
        if clause.effective_date:
            parts.append(f"có hiệu lực từ {clause.effective_date}")
        if clause.status:
            parts.append(f"trạng thái: {clause.status}")

        # Take first sentence of the clause text (up to 200 chars)
        text = clause.text.strip()
        first_sentence = text.split(".")[0][:200].strip()
        if first_sentence:
            parts.append(f"Nội dung: {first_sentence}.")

        return " ".join(parts)
